name: busy_items_app
description: Busy-like Items App

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  riverpod: ^3.2.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.2.1
  go_router: ^17.1.0
  cached_network_image: ^3.4.0
  intl: ^0.19.0
  google_fonts: ^6.1.0
  animations: ^2.1.1
  fluttertoast: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
